import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — BeKnown',
  description: 'Terms of service for BeKnown, the AI-verified professional profile platform.',
  alternates: {
    canonical: 'https://beknown.no-humans.app/terms',
  },
};

export default function TermsPage() {
  return (
    <main className="flex-1 max-w-3xl mx-auto px-6 py-16">
      <h1 className="font-heading text-4xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-[#71717A] mb-8">Last updated: March 22, 2026</p>

      <div className="space-y-8 text-[#A1A1AA] leading-relaxed">
        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">1. Acceptance of Terms</h2>
          <p>
            By using BeKnown (beknown.no-humans.app), you agree to these terms. If you don&apos;t agree, don&apos;t use the service.
            BeKnown is operated by no-humans.app.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">2. What BeKnown Is</h2>
          <p>
            BeKnown is a free tool that generates professional profiles from AI conversation history. You provide
            a JSON output from your AI assistant, and we create a shareable profile page. There are no accounts,
            no subscriptions, and no fees.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">3. Your Profile Content</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>You are responsible for the content of your profile, even though it was generated by an AI.</li>
            <li>Do not submit profiles that contain false information, offensive content, or another person&apos;s personal data.</li>
            <li>Profiles are public. Anyone with your profile URL can view it.</li>
            <li>By submitting a profile, you grant BeKnown a license to host and display it publicly.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">4. Verification System</h2>
          <p>
            BeKnown uses one-time verification codes (nonces) to confirm that profiles are generated in real time.
            Attempting to circumvent the verification system, reuse expired codes, or submit fabricated profiles
            is prohibited.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">5. Prohibited Uses</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>Creating profiles that impersonate other people.</li>
            <li>Submitting fabricated or manually crafted JSON to misrepresent your skills.</li>
            <li>Using automated tools to mass-generate profiles.</li>
            <li>Attempting to exploit, attack, or disrupt the service.</li>
            <li>Scraping profile data for commercial purposes.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">6. No Warranty</h2>
          <p>
            BeKnown is provided &quot;as is&quot; without warranties of any kind. We do not guarantee that profiles will
            be accurate, that the service will be available at all times, or that AI-generated content will be free
            from errors. The AI&apos;s assessment of your skills and experience is based on conversation history and may
            not be complete or fully accurate.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, BeKnown and no-humans.app shall not be liable for any indirect,
            incidental, special, or consequential damages arising from your use of the service. This includes but
            is not limited to damages from lost employment opportunities, inaccurate profile information, or service
            interruptions.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">8. Content Removal</h2>
          <p>
            We reserve the right to remove any profile at any time, for any reason, without notice. If you want
            your own profile removed, contact us through{' '}
            <a href="https://no-humans.app" target="_blank" rel="noopener noreferrer" className="text-[#E5C07B] hover:underline">
              no-humans.app
            </a>.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">9. Intellectual Property</h2>
          <p>
            The BeKnown name, logo, and platform design are the property of no-humans.app. Your profile content
            remains yours — we only host and display it. The AI-generated content in your profile is subject to
            the terms of service of whatever AI provider generated it (OpenAI, Anthropic, Google, etc.).
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">10. Changes to Terms</h2>
          <p>
            We may update these terms at any time. Continued use of BeKnown after changes are posted constitutes
            acceptance of the updated terms. Material changes will be reflected in the &quot;Last updated&quot; date above.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">11. Governing Law</h2>
          <p>
            These terms are governed by applicable law. Any disputes will be resolved in the jurisdiction where
            no-humans.app is established.
          </p>
        </section>

        <section>
          <h2 className="font-heading text-xl font-semibold text-[#F5F5F5] mb-3">12. Contact</h2>
          <p>
            Questions about these terms? Visit{' '}
            <a href="https://no-humans.app" target="_blank" rel="noopener noreferrer" className="text-[#E5C07B] hover:underline">
              no-humans.app
            </a>{' '}
            for contact information.
          </p>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t border-[#27272A]">
        <Link href="/" className="text-[#71717A] text-sm hover:text-[#F5F5F5] transition-colors">
          &larr; Back to home
        </Link>
      </div>
    </main>
  );
}
